export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="robbyrussell"

plugins=(
		git
		dirhistory
		vi-mode
		zsh-syntax-highlighting
		zsh-autosuggestions
	)


eval `dircolors ~/.linux_setup/zsh/bliss.dircolors`
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
source $ZSH/oh-my-zsh.sh
source ~/.linux_setup/zsh catppuccin_mocha-zsh-syntax-highlighting.zsh

alias vim="nvim"
