export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="robbyrussell"

plugins=(
		git
		dirhistory
		vi-mode
		zsh-syntax-highlighting
		zsh-autosuggestions
	)


eval `dircolors ~/.dot/zsh/bliss.dircolors`
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
source $ZSH/oh-my-zsh.sh
source ~/.dot/zsh catppuccin_mocha-zsh-syntax-highlighting.zsh

alias vim="nvim"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
